FROM ubuntu:focal

RUN apt-get update -qqy
RUN apt-get upgrade -qqy
RUN apt-get install -y libssl-dev libgomp1
ADD ./redis-stack /var/cache/apt/redis-stack/
COPY ./etc/entrypoint.redis-stack.sh /entrypoint.sh
RUN chmod a+x /entrypoint.sh
RUN touch /.dockerenv
RUN dpkg -i /var/cache/apt/redis-stack/redis-stack*.deb
RUN dpkg -i /var/cache/apt/redis-stack/redisinsight*.deb
RUN rm -rf /var/cache/apt

EXPOSE 6379 8001

ENTRYPOINT ["/entrypoint.sh"]
