#!/bin/sh

OS=`uname -s`
ARCH=`uname -m`

#### placeholder for redis-stack-server script
if [ ${OS} == "Darwin" ]; then
    if [ ${ARCH} == "x86_64" ]; then
        BASEDIR=/usr/local/
        REDIS_DATA_DIR=${BASEDIR}/var/db/redis
    else
        BASEDIR=/opt/redis-stack
        REDIS_DATA_DIR=${BASEDIR}/var/db/redis
    fi
else {
    # TODO add proper linux support
    BASEDIR=/opt/redis-stack
    REDIS_DATA_DIR=/var/db/redis
}
fi

if [ ! -d ${REDIS_DATA_DIR} ]; then
    mkdir -p ${REDIS_DATA_DIR}
    if [ $? -ne 0 ]; then
        echo "Unable to write to ${REDIS_DATA_DIR} as the current user. Exiting."
        exit 1
    fi
fi

MODULEDIR=${BASEDIR}/lib

cd ${BASEDIR}
CMD=${BASEDIR}/bin/redis-server
if [ -f $1 ]; then
    CONFFILE=$1
    shift
fi

${CMD} \
${CONFFILE} -- \
--dir ${REDIS_DATA_DIR} \
--protected-mode no \
--daemonize no \
--loadmodule ${BASEDIR}/lib/redisearch.so \
${REDISEARCH_ARGS} \
--loadmodule ${BASEDIR}/lib/redisgraph.so \
${REDISGRAPH_ARGS} \
--loadmodule ${BASEDIR}/lib/redistimeseries.so \
${REDISTIMESERIES_ARGS} \
--loadmodule ${BASEDIR}/lib/rejson.so \
${REJSON_ARGS} \
--loadmodule ${BASEDIR}/lib/redisbloom.so \
${REDISBLOOM_ARGS} \
S*