#!/bin/sh

for i in redis-cli redis-benchmark redis-check-aof redis-check-rdb redis-cli redis-sentinel redis-server redis-stack-server; do
    if [ ! -e /usr/bin/$i ]; then
        ln -s /opt/redis-stack/bin/$i /usr/bin/$i
    fi
done

if [ -f /usr/bin/systemctl ]; then
    systemctl enable redis-stack-server
    systemctl start redis-stack-server
fi
