FROM ubuntu:jammy

RUN apt-get update -qqy --fix-missing
RUN apt-get upgrade -qqy
RUN apt-get install -y dumb-init gdebi-core
ADD ./redis-stack /var/cache/apt/redis-stack/
RUN mkdir -p /data/redis /data/redisinsight
RUN touch /.dockerenv

{% if docker_type == 'redis-stack-server' %}
RUN gdebi -n /var/cache/apt/redis-stack/redis-stack-server*.deb
{% elif docker_type == 'redis-stack' %}
RUN apt-get install -y libsecret-1-0
RUN gdebi -n /var/cache/apt/redis-stack/redis-stack-server*.deb
RUN gdebi -n /var/cache/apt/redis-stack/redisinsight*.deb
{% endif %}
RUN apt remove -y gdebi
RUN apt autoremove -y
RUN rm -rf /var/cache/apt

COPY ./etc/scripts/entrypoint.sh /entrypoint.sh
RUN chmod a+x /entrypoint.sh

{% if docker_type == 'redis-stack-server' %}
EXPOSE 6379
{% elif docker_type == 'redis-stack' %}
EXPOSE 6379 8001
{% endif %}

{% if docker_type == 'redis-stack' %}
COPY etc/envfiles/insight.docker.env /opt/redis-stack/share/redisinsight/.env
RUN chmod 0555 /opt/redis-stack/share/redisinsight/.env
{% endif %}

ENV REDISBLOOM_ARGS ""
ENV REDISEARCH_ARGS ""
ENV REDISJSON_ARGS ""
ENV REDISTIMESERIES_ARGS ""
ENV REDISGRAPH_ARGS ""
ENV REDIS_ARGS ""

CMD ["/entrypoint.sh"]
