name: Docker

on:
  workflow_call:
    inputs:
      pythonversion:
        required: false
        type: string
        default: "3.10"
      arch:
        required: false
        type: string
        default: x86_64
      platform:
        required: true
        type: string
    secrets:
      DOCKERHUB_TOKEN:
        required: true
      DOCKERHUB_USERNAME:
        required: true

jobs:


  dockers:
    name: ${{matrix.package}} docker
    strategy:
      matrix:
        package: ['redis-stack-server', 'redis-stack']

    runs-on: ubuntu-latest
    steps:

      - name: determine if in fork
        id: iamafork
        run: |
          amfork=`jq '.pull_request.head.repo.fork' $GITHUB_EVENT_PATH`
          echo "am I fork: ${amfork}"
          echo "IAMAFORK=$amfork" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v3
      - name: install python
        uses: actions/setup-python@v4
        with:
          python-version: "${{inputs.pythonversion}}"

      - uses: actions/cache@v3
        with:
          path: |
            /var/cache/apt/archives/*.deb
            /var/cache/yum
            ~/.cache/pip
            ~/.cache/pypoetry
            ~/.local/share/gem
          key: pypoetry-${{hashFiles('**/pyproject.toml', '.github/workflows/*.yml')}}-${{inputs.platform}}-${{inputs.arch}}-package

      - name: install poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-in-project: true
          virtualenvs-create: true
          installer-parallel: true

      - uses: actions/download-artifact@v3
        with:
          name: redis-stack-server-${{inputs.platform}}-${{inputs.arch}}.deb
          path: redis-stack
      - uses: actions/download-artifact@v3
        with:
          name: redisinsight-web-${{inputs.platform}}-${{inputs.arch}}.deb
          path: redis-stack
      - name: display structure
        run: ls -R

      # we have one version - so getting the value from config is
      # cleaner
      - name: get package version
        id: get_version
        run: |
          poetry install
          source .venv/bin/activate
          realversion=`invoke version -p redis-stack-server -d true`
          echo "VERSION=$realversion" >> $GITHUB_OUTPUT

      - uses: docker/setup-qemu-action@v2

      # https://github.com/docker/buildx/issues/1509
      - uses: docker/setup-buildx-action@v2
        with:
          install: true
          version: v0.9.1

      - name: generate docker file
        run: |
          source .venv/bin/activate
          invoke dockergen -p ${{ matrix.package }}

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and publish docker
        run: |
          source .venv/bin/activate
          invoke dockerbuild -a ${{inputs.arch}} -d envs/dockers/Dockerfile.${{ matrix.package }} -t redisfab/${{matrix.package}}:${{steps.get_version.outputs.VERSION}}-${{inputs.arch}} -r . -b

      - name: test docker build
        if: ${{ inputs.arch != 'arm64' }}
        run: |
          source .venv/bin/activate
          invoke test-ci-dockers -d ${{matrix.package}} -a ${{inputs.arch}} -v ${{steps.get_version.outputs.VERSION}}-${{inputs.arch}}
