name: Docker

on:
  workflow_run:
    workflows: ["Bionic"]
    types:
      - completed

concurrency:
  group: appimage-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:


 x86_64-appimage:
   uses: ./.github/workflows/REUSABLE_APPIMAGE.yml
   with:
     arch: x86_64
     platform: bionic
     osnick: ubuntu18.04
     pythonversion: "3.10"
   secrets: inherit