name: Bionic

on:
  workflow_call:

concurrency:
  group: bionic-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

 arm64-bionic:
   uses: ./.github/workflows/REUSABLE_ARM64.yml
   with:
     image_name: ubuntu:bionic
     platform: bionic
     osname: Linux
     osnick: ubuntu18.04
     arch: arm64
     target: deb
     build_deps: apt-get update && apt-get install -y build-essential libssl-dev python3 python3-pip
     pythonversion: "3.10"
   secrets: inherit

 x86_64-bionic:
   uses: ./.github/workflows/REUSABLE_X64.yml
   with:
     image_name: ubuntu:bionic
     platform: bionic
     osname: Linux
     osnick: ubuntu18.04
     arch: x86_64
     target: deb
     build_deps: apt-get update && apt-get install -y build-essential libssl-dev python3 python3-pip jq wget
     pythonversion: "3.10"
   secrets: inherit