name: RHEL8

on:
  workflow_call:

  pull_request:

  workflow_dispatch:

concurrency:
  group: rhel8-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

 x86-64_rhel8:
   uses: ./.github/workflows/REUSABLE_X64.yml
   with:
     image_name: oraclelinux:8
     platform: rhel8
     osname: Linux
     osnick: rhel8
     arch: x86_64
     target: rpm
     pythonversion: "3.10"
     build_deps: |
       dnf install -y oracle-epel-release-el8
       dnf install -y gcc make jemalloc-devel openssl-devel tar git python3 python3-pip jq wget
   secrets: inherit
