name: Jammy

on:
  workflow_call:

  workflow_dispatch:

concurrency:
  group: jammy-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

 arm64-jammy:
   uses: ./.github/workflows/REUSABLE_ARM64.yml
   name: Jammy [Arm64]
   with:
     image_name: ubuntu:jammy
     platform: jammy
     osname: Linux
     osnick: ubuntu22.04
     arch: arm64
     target: deb
     build_deps: apt-get update && apt-get upgrade -y && apt-get install -y build-essential libssl-dev python3 python3-pip
     pythonversion: "3.10"
   secrets: inherit

 x86_64-jammy:
   uses: ./.github/workflows/REUSABLE_X64.yml
   name: Jammy [x86_64]
   with:
     image_name: ubuntu:jammy
     platform: jammy
     osname: Linux
     osnick: ubuntu22.04
     arch: x86_64
     target: deb
     build_deps: apt-get update && apt-get install -y build-essential libssl-dev python3 python3-pip jq wget
     pythonversion: "3.10"
   secrets: inherit
