name: 'Test Report'
on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          artifact: /test-report-(.*)/
          name: 'Test Results $1'
          path: '*.xml'
          reporter: java-junit
          list-suites: all
          list-tests: all
          max-annotations: 10